name: Deploy to production

#gatilhos
on: 
  push:
    branches:
      - main
#jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1 checkout do codigo
      - name: checkout code
        uses: actions/checkout@v2

      # 2 configurar node
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # 3 instalar dependencias
      - name: install dependencies
        run: npm install

      # 4 testes
      - name: run tests
        run: npm test

      # 5 buildar
      - name: build
        run: npm run build
        env:
          # ignorar avisos
          CI: false

      # 6 configuração do AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      # 7 enviar os arquivos para o S3
      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://sandbox-devops-cbkremer/ --exclude ".git/*" --delete --exact-timestamps






        
      