name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests
      - name: Run tests
        run: npm test

      # 5. Build app
      - name: Build
        run: npm run build
        env:
          CI: false

      # 6. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 7. Terraform init
      - name: Terraform Init
        run: terraform -chdir=infra init

      # 8. Terraform plan
      - name: Terraform Plan
        run: terraform -chdir=infra plan -out=tfplan

      # 9. Terraform apply
      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve tfplan

      # 10. Setup AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 11. Deploy build to S3
      - name: Deploy to S3
        run: |
          BUCKET_NAME=$(terraform -chdir=infra output -raw bucket_name)
          echo "Deploying to bucket: $BUCKET_NAME"
          aws s3 sync build/ s3://$BUCKET_NAME/ --exclude ".git/*" --delete --exact-timestamps
